using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Bindings;

/// <summary>
/// [ViewModel]属性が付与されたクラスからバインディングメタデータを収集するソースジェネレータ.
/// </summary>
[Generator]
public class ViewModelGenerator : IIncrementalGenerator
{
    private const string ViewModelAttributeFullName = "Bindings.ViewModelAttribute";
    private const string ModelAttributeName = "ModelAttribute";
    private const string SchemaAttributeName = "SchemaAttribute";

    private const string AttributesSourceCode = @"// <auto-generated/>

namespace Bindings
{
    /// <summary>ViewModelとしてマークするための属性.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public sealed class ViewModelAttribute : System.Attribute
    {
        public bool RequireBindImplementation { get; }

        public ViewModelAttribute(bool requireBindImplementation = false)
            => RequireBindImplementation = requireBindImplementation;
    }

    /// <summary>Modelフィールドまたはプロパティをマークするための属性.</summary>
    [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property)]
    public sealed class ModelAttribute : System.Attribute { }

    /// <summary>バインディングスキーマをマークするための属性.</summary>
    [System.AttributeUsage(
        System.AttributeTargets.Field | System.AttributeTargets.Property | System.AttributeTargets.Method,
        AllowMultiple = true)]
    public sealed class SchemaAttribute : System.Attribute
    {
        public string BindingPath { get; }
        public int Id { get; }
        public string Format { get; }

        public SchemaAttribute(string bindingPath, int id = 0, string format = """")
        {
            BindingPath = bindingPath;
            Id = id;
            Format = format;
        }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register attribute definitions so they can be referenced in user code.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "BindingsAttributes.g.cs",
            SourceText.From(AttributesSourceCode, Encoding.UTF8)));

        // Find class declarations annotated with [ViewModel].
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax,
                transform: (ctx, _) => GetViewModelClassDeclaration(ctx))
            .Where(t => t.found)
            .Select((t, _) => t.classDecl);

        // Combine with the compilation and generate code.
        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(provider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    /// <summary>
    /// [ViewModel]属性が付与されたクラス宣言を返す.
    /// </summary>
    private static (ClassDeclarationSyntax classDecl, bool found) GetViewModelClassDeclaration(
        GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;

        foreach (var attrList in classDecl.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attr).Symbol is not IMethodSymbol methodSymbol)
                continue;

            if (methodSymbol.ContainingType.ToDisplayString() == ViewModelAttributeFullName)
                return (classDecl, true);
        }

        return (classDecl, false);
    }

    /// <summary>
    /// クラスシンボルから<see cref="GenerationContext"/>を構築する.
    /// </summary>
    internal static GenerationContext BuildGenerationContext(INamedTypeSymbol classSymbol)
    {
        // RequireBindImplementation: [ViewModel] 属性の引数.
        bool requireBindImplementation = false;
        var viewModelAttr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ViewModelAttributeFullName);
        if (viewModelAttr != null && viewModelAttr.ConstructorArguments.Length > 0)
        {
            requireBindImplementation = viewModelAttr.ConstructorArguments[0].Value is true;
        }

        // AlreadySerializable: [Serializable] が既に付与されているかどうか.
        bool alreadySerializable = classSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == "System.SerializableAttribute");

        // Models: [Model] が付与されたフィールドとプロパティ.
        var modelFields = classSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.GetAttributes().Any(a => a.AttributeClass?.Name == ModelAttributeName))
            .Select(f => (typeFullName: f.Type.ToDisplayString(), name: f.Name));

        var modelProperties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == ModelAttributeName))
            .Select(p => (typeFullName: p.Type.ToDisplayString(), name: p.Name));

        var models = modelFields.Concat(modelProperties).ToArray();

        // Schemas: [Schema] が付与されたフィールドとプロパティ.
        var schemaFields = classSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .SelectMany(f => f.GetAttributes()
                .Where(a => a.AttributeClass?.Name == SchemaAttributeName)
                .Select(BuildSchemaEntry));

        var schemaProperties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .SelectMany(p => p.GetAttributes()
                .Where(a => a.AttributeClass?.Name == SchemaAttributeName)
                .Select(BuildSchemaEntry));

        var schemas = schemaFields.Concat(schemaProperties).ToArray();

        // SchemaMethods: [Schema] が付与されたメソッド.
        var schemaMethods = classSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary)
            .SelectMany(m => m.GetAttributes()
                .Where(a => a.AttributeClass?.Name == SchemaAttributeName)
                .Select(BuildSchemaMethodEntry))
            .ToArray();

        return new GenerationContext(requireBindImplementation, alreadySerializable, models, schemas, schemaMethods);
    }

    private static (string bindingPath, int id, string format) BuildSchemaEntry(AttributeData attr)
    {
        var args = attr.ConstructorArguments;
        return (
            bindingPath: args.Length > 0 ? args[0].Value?.ToString() ?? string.Empty : string.Empty,
            id: args.Length > 1 && args[1].Value is int id ? id : 0,
            format: args.Length > 2 ? args[2].Value?.ToString() ?? string.Empty : string.Empty);
    }

    private static (string bindingPath, int id) BuildSchemaMethodEntry(AttributeData attr)
    {
        var args = attr.ConstructorArguments;
        return (
            bindingPath: args.Length > 0 ? args[0].Value?.ToString() ?? string.Empty : string.Empty,
            id: args.Length > 1 && args[1].Value is int id ? id : 0);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarations)
    {
        foreach (var classDecl in classDeclarations)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            var generationContext = BuildGenerationContext(classSymbol);
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classDecl.Identifier.Text;

            var code = GeneratePartialClass(namespaceName, className, generationContext);
            context.AddSource($"{className}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    /// <summary>
    /// GenerationContext をもとにプレースホルダーの partial クラスを生成する.
    /// 実際のバインディングコード生成は後続のステップで実装する.
    /// </summary>
    private static string GeneratePartialClass(
        string namespaceName,
        string className,
        GenerationContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
