//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bindings.GeneratorCore {
    using Bindings.GeneratorCore;
    using System;
    
    
    public partial class ViewModelTemplate : ViewModelTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            this.Write("#nullable enable\n");
 if (HasNamespace) { 
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.Namespace ));
            this.Write("\n{\n");
 } 
 foreach (var (typeKeyword, typeName) in Context.ContainingTypes) { 
            this.Write("public partial ");
            this.Write(this.ToStringHelper.ToStringWithCulture( typeKeyword ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( typeName ));
            this.Write("\n{\n");
 } 
 if (!Context.AlreadySerializable) { 
            this.Write("[global::System.Serializable]\n");
 } 
            this.Write("public partial ");
            this.Write(this.ToStringHelper.ToStringWithCulture( TypeKeyword ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.ClassName ));
            this.Write(" : global::Bindings.IViewModel\n{\n    private readonly global::Bindings.IMvvmPubli" +
                    "sher _publisher;\n");
 foreach (var schemaField in Context.SchemaFields) { 
            this.Write("\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture( schemaField.FieldTypeName ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ToPropertyName(schemaField.FieldName) ));
            this.Write("\n    {\n        get => ");
            this.Write(this.ToStringHelper.ToStringWithCulture( schemaField.FieldName ));
            this.Write(";\n");
 if (!Context.IsReadOnly) { 
            this.Write("        set\n        {\n            ");
            this.Write(this.ToStringHelper.ToStringWithCulture( schemaField.FieldName ));
            this.Write(" = value;\n            PublishRebindMessage();\n        }\n");
 } 
            this.Write("    }\n");
 } 
            this.Write("\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.ClassName ));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture( ConstructorParamList ));
            this.Write(")\n    {\n");
 foreach (var field in Context.RequiredFields) { 
            this.Write("        ");
            this.Write(this.ToStringHelper.ToStringWithCulture( field.FieldName ));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ToParamName(field.FieldName) ));
            this.Write(";\n");
 } 
            this.Write(@"        _publisher = publisher;
    }

    public void NotifyCompletedBind() => OnPostBind();

    partial void OnPostBind();

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private void PublishRebindMessage()
    {
        _publisher.PublishRebindMessage<");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewModelFullName ));
            this.Write(">();\n    }\n}\n");
 foreach (var _ in Context.ContainingTypes) { 
            this.Write("}\n");
 } 
 if (HasNamespace) { 
            this.Write("}\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class ViewModelTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
