//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bindings.GeneratorCore {
    using Bindings.GeneratorCore;
    using System;
    
    
    public partial class ViewTemplate : ViewTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            this.Write("#nullable enable\n");
 if (HasNamespace) { 
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.Namespace ));
            this.Write("\n{\n");
 } 
 foreach (var (typeKeyword, typeName) in Context.ContainingTypes) { 
            this.Write("public partial ");
            this.Write(this.ToStringHelper.ToStringWithCulture( typeKeyword ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( typeName ));
            this.Write("\n{\n");
 } 
            this.Write("[global::System.Serializable]\npublic sealed partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewClassName ));
            this.Write(" : global::Bindings.IView<");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewModelFullName ));
            this.Write(">\n{\n    [global::System.NonSerialized]\n    private ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewModelFullName ));
            this.Write(" _viewModel");
            this.Write(this.ToStringHelper.ToStringWithCulture( VmFieldInit ));
            this.Write(";\n");
 foreach (var field in OrderedFields) { 
            this.Write("\n");
 if (!string.IsNullOrEmpty(field.Tooltip)) { 
            this.Write("    [global::UnityEngine.Tooltip(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture( field.Tooltip ));
            this.Write("\")]\n");
 } 
            this.Write("    [global::UnityEngine.SerializeField]\n    private global::");
            this.Write(this.ToStringHelper.ToStringWithCulture( field.TypePart ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( field.FieldName ));
            this.Write(" = null!;\n");
 } 
            this.Write("\n    void global::Bindings.IView<");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewModelFullName ));
            this.Write(">.Initialize(");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewModelFullName ));
            this.Write(" viewModel)\n    {\n        _viewModel = viewModel;\n    }\n");
 if (!Context.RequireBindImplementation) { 
            this.Write("\n    global::System.Threading.Tasks.ValueTask global::Bindings.IView.BindAsync(gl" +
                    "obal::System.Threading.CancellationToken _)\n    {\n        BindAll();\n        ret" +
                    "urn default;\n    }\n");
 } 
            this.Write("\n    private void BindAll()\n    {\n");
            this.Write(this.ToStringHelper.ToStringWithCulture( WriteFieldBindings("        ") ));
            this.Write("\n");
            this.Write(this.ToStringHelper.ToStringWithCulture( WriteMethodBindings("        ") ));
            this.Write("\n        OnPostBind();\n        _viewModel.NotifyCompletedBind();\n    }\n\n    parti" +
                    "al void OnPostBind();\n}\n");
 foreach (var _ in Context.ContainingTypes) { 
            this.Write("}\n");
 } 
 if (HasNamespace) { 
            this.Write("}\n");
 } 
            this.Write("\n#if UNITY_EDITOR || DEVELOPMENT_BUILD || !DISABLE_DEBUGTOOLKIT\n");
 if (HasNamespace) { 
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Context.Namespace ));
            this.Write("\n{\n");
 } 
 foreach (var (typeKeyword, typeName) in Context.ContainingTypes) { 
            this.Write("public partial ");
            this.Write(this.ToStringHelper.ToStringWithCulture( typeKeyword ));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture( typeName ));
            this.Write("\n{\n");
 } 
            this.Write("public sealed partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ViewClassName ));
            this.Write(" : global::Bindings.IMvvmSubscriber<global::Bindings.DebugBindMessage>\n{\n    void" +
                    " global::Bindings.IMvvmSubscriber<global::Bindings.DebugBindMessage>.OnReceivedM" +
                    "essage(global::Bindings.DebugBindMessage message)\n    {\n        message.BindTo(t" +
                    "his);\n");
            this.Write(this.ToStringHelper.ToStringWithCulture( WriteFieldBindings("        ") ));
            this.Write("\n        OnPostBind();\n        _viewModel.NotifyCompletedBind();\n    }\n}\n");
 foreach (var _ in Context.ContainingTypes) { 
            this.Write("}\n");
 } 
 if (HasNamespace) { 
            this.Write("}\n");
 } 
            this.Write("#endif\n");
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class ViewTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
